baseURL = "https://coco-grove.netlify.app/"
title = "cocogrove"
theme = "PaperMod"
languageCode = "ko"
defaultContentLanguage = "ko"
paginate = 10
params.assets.search = true

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowWordCount = true
  defaultTheme = "auto"  # dark/light/auto

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 5
